# ---------------------------------------------------------------
# Site Information Settings
# References: https://github.com/miccall/hexo-theme-Mic_Theme
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/logo_miccall.png"
    keywords: 奶爸 程序员 IT  
    backgroundpic : "img/bg.jpg"

Intro:
    name: Monor
    slogan: "What i can't create <br/> I don't understand"
    HeadButton: HOWDY

Nav:
    Home_name: Home
    is_use_categories : true 
    categories_name: Categories
    is_use_archives : true
    archives_name: Archives
    
    #Social
    # for more icons, please see http://fontawesome.io/icons/#brand
    icon:
        github: https://github.com/huangxinping
        500px: http://500px.com
        
    pages:
        # 简历: 
        #     link: "/about/"
        #团队:
        #    link: "/group/"
        #图库:
        #    link: "/gallery/"
        #标签:
        #    link: "/tag/"
        #自定义标签名
        #   link：“路径”

MainFirst:
    name: Monor Huang
    description: Super Dad, Software Engineer, CTO   
    pic_url: /images/me.jpg
    goto_ulr: "https://github.com/huangxinping"

# Gallery :
#     title: Mr.metro 
#     description: Just another fine responsive 

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# default dark funky okaidia twilight coy solarized  可选项  
# link to review : http://prismjs.com/index.html   官网预览
prism: coy

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: changyan
    shortname: http-www-huangxinping-com 
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid: cyvk23DNF
    changyan_conf: prod_1ac0c5be7ecbf7b4e323782001fb0bab
    changyan_thread_key_type: path
    # 使用 valine 请先执行 npm install valine --save
    valine: # Valine Comment System https://github.com/xCss/Valine
       on: false
       appId: 'JkVWmjOvlEGJO5XFsqEDYuTF-gzGzoHsz'
       appKey: 'XjRBQrPethbRhwP7bfQEMxQX'
       notify: true
       verify: false
       placeholder: Please leave your footprints
       avatar: ''
       avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
       pageSize: 10 # comments of one page

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views
leancloud:
    enable: false
    app_id: JkVWmjOvlEGJO5XFsqEDYuTF-gzGzoHsz
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"


# Mathjax 支持库 
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML